# Docker Compose file for easier build and test in local machine
version: "3.8"
services:
  flask_app:
    container_name: fmc_thousandeyes_dashboard
    build: ./flask_app
    ports:
      - 5000:5000
    environment:
      - FMC_HOSTNAME=${FMC_HOSTNAME}
      - FMC_USERNAME=${FMC_USERNAME}
      - FMC_PASSWORD=${FMC_PASSWORD}
      - THOUSAND_EYES_TOKEN=${THOUSAND_EYES_TOKEN}
    volumes:
      - ./flask_app:/app
